version: "3.7"

services:
  bazarr:
    container_name: bazarr
    image: cr.hotio.dev/hotio/bazarr
    ports:
      - "9094:6767"
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - /volume1/docker/bazarr/config:/config:rw
      - /volume1/Multimedia/Sorted/Movies:/movies:rw
      - '/volume1/Multimedia/Sorted/TV Shows:/tv:rw'
    restart: unless-stopped
 ##	Place holder for network option until network scheme determined  
 #	network:
